#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBackendProductos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SeriesPeliculasDB")]
	public partial class SpProductoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public SpProductoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SeriesPeliculasDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SpProductoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SpProductoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SpProductoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SpProductoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LIST_PRODUCT")]
		public ISingleResult<SP_LIST_PRODUCTResult> SP_LIST_PRODUCT()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_LIST_PRODUCTResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERT_PRODUCT")]
		public int SP_INSERT_PRODUCT([global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_ID_PRODUCT", DbType="Decimal(18,0)")] System.Nullable<decimal> p_ID_PRODUCT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_NAME_PRODUCT", DbType="NVarChar(50)")] string p_NAME_PRODUCT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_FK_ID_CATEGORY", DbType="Decimal(18,0)")] System.Nullable<decimal> p_FK_ID_CATEGORY)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_ID_PRODUCT, p_NAME_PRODUCT, p_FK_ID_CATEGORY);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LIST_PRODUCT_FILTER")]
		public ISingleResult<SP_LIST_PRODUCT_FILTERResult> SP_LIST_PRODUCT_FILTER([global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_FK_ID_CATEGORY", DbType="Decimal(18,0)")] System.Nullable<decimal> p_FK_ID_CATEGORY)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_FK_ID_CATEGORY);
			return ((ISingleResult<SP_LIST_PRODUCT_FILTERResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_LIST_PRODUCTResult
	{
		
		private System.Nullable<decimal> _ID_PRODUCT;
		
		private string _NAME_PRODUCT;
		
		private decimal _FK_ID_CATEGORY;
		
		public SP_LIST_PRODUCTResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRODUCT", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ID_PRODUCT
		{
			get
			{
				return this._ID_PRODUCT;
			}
			set
			{
				if ((this._ID_PRODUCT != value))
				{
					this._ID_PRODUCT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME_PRODUCT", DbType="NVarChar(50)")]
		public string NAME_PRODUCT
		{
			get
			{
				return this._NAME_PRODUCT;
			}
			set
			{
				if ((this._NAME_PRODUCT != value))
				{
					this._NAME_PRODUCT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_ID_CATEGORY", DbType="Decimal(18,0) NOT NULL")]
		public decimal FK_ID_CATEGORY
		{
			get
			{
				return this._FK_ID_CATEGORY;
			}
			set
			{
				if ((this._FK_ID_CATEGORY != value))
				{
					this._FK_ID_CATEGORY = value;
				}
			}
		}
	}
	
	public partial class SP_LIST_PRODUCT_FILTERResult
	{
		
		private System.Nullable<decimal> _ID_PRODUCT;
		
		private string _NAME_PRODUCT;
		
		private decimal _FK_ID_CATEGORY;
		
		public SP_LIST_PRODUCT_FILTERResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PRODUCT", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ID_PRODUCT
		{
			get
			{
				return this._ID_PRODUCT;
			}
			set
			{
				if ((this._ID_PRODUCT != value))
				{
					this._ID_PRODUCT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME_PRODUCT", DbType="NVarChar(50)")]
		public string NAME_PRODUCT
		{
			get
			{
				return this._NAME_PRODUCT;
			}
			set
			{
				if ((this._NAME_PRODUCT != value))
				{
					this._NAME_PRODUCT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_ID_CATEGORY", DbType="Decimal(18,0) NOT NULL")]
		public decimal FK_ID_CATEGORY
		{
			get
			{
				return this._FK_ID_CATEGORY;
			}
			set
			{
				if ((this._FK_ID_CATEGORY != value))
				{
					this._FK_ID_CATEGORY = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
